---

- name: Checkout repository
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.destination }}"
    accept_hostkey: yes
    key_file: "{{ ssh_user_homedir }}/.ssh/id_rsa"
  with_items: "{{ repositories }}"

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ create_directories }}"

- name: Run Composer on checked out repository
  composer:
    command: install
    working_dir: "{{ item }}"
  with_items: "{{ composer_install }}"

- name: Create symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ create_symlinks }}"

- name: Make directories writeable
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items: "{{ writeable_dirs }}"
