---

- name: Checkout repository
  git:
    repo: "{{ repository_url }}"
    dest: "{{ checkout_destination }}"
    accept_hostkey: yes
    key_file: "{{ ssh_user_homedir }}/.ssh/id_rsa"

- name: Create config directory
  file:
    path: "{{ config_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Run composer install on checked out repository
  composer:
    command: install
    working_dir: "{{ checkout_destination }}"

- name: Create symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ create_symlinks }}"

- name: Make directories writeable
  file:
    path: "{{ checkout_destination }}"
    state: directory
    mode: 0777
  with_items: "{{ writeable_dirs }}"
